version: '3'
services:
  app:
    image: openjdk:17-jdk-alpine
    container_name: springboot-app
    volumes:
      - ./target/Pokemine-0.0.1-SNAPSHOT.jar:/app/Pokemine-0.0.1-SNAPSHOT.jar
    working_dir: /app
    ports:
      - "9089:8080"
    command: ["java", "-jar", "Pokemine-0.0.1-SNAPSHOT.jar"]
